Fix output typo in script/generate & add script/config #sanity

diff --git a/code-samples/script/edit b/code-samples/script/edit
--- a/code-samples/script/edit
+++ b/code-samples/script/edit
@@ -1,7 +1,5 @@
 #! /bin/bash
 
-# ⚠️  This makes a LOT of assumptions. It will probably break for you.
-
 if [ "$#" -ne 2 ]; then
   echo "Usage: ./script/edit [api_name] [api_version]"
   echo
@@ -14,11 +12,8 @@ API_NAME="$1"
 API_VERSION="$2"
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-CODE_SAMPLES_DIR="$( dirname "$SCRIPT_DIR" )"
-GOOGLEAPIS_DIR="$( dirname "$CODE_SAMPLES_DIR" )"
-GOOGLE_DIR="$GOOGLEAPIS_DIR/google"
 
-GAPIC_CONFIG="$( find "$GOOGLE_DIR" -type f -name "${API_NAME}_gapic.yaml" | grep "/$API_VERSION/" )"
+GAPIC_CONFIG="$( $SCRIPT_DIR/config "$API_NAME" "$API_VERSION" )"
 
 if [ -n "$GAPIC_CONFIG" ]; then
 	if [ -z "$EDITOR" ]; then
@@ -27,6 +22,8 @@ if [ -n "$GAPIC_CONFIG" ]; then
 		EDITOR=vi
 	fi
   $EDITOR "$GAPIC_CONFIG"
+  exit 0
 else
-  echo "No GAPIC configuration file found for $API_NAME $API_VERSION"
+  echo "GAPIC config not found for $API_NAME $API_VERSION"
+  exit 1
 fi
